# gets the docker image of ruby 2.5 and lets us build on top of that
FROM ruby:2.6.5

# install rails dependencies
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get update -qq && apt-get install -y -qq libpq-dev libv8-dev
RUN apt-get install -y nodejs
RUN wget -q -O - https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install yarn

# Set an environment variable where the Rails app is installed to inside of Docker image
ENV RAILS_ROOT /var/www/imp
RUN mkdir -p $RAILS_ROOT

# create a folder /imp in the docker container and go into that folder
WORKDIR $RAILS_ROOT

# Setting env up
#ENV RAILS_ENV='production'
#ENV RACK_ENV='production'

# Copy the Gemfile and Gemfile.lock from app root directory into the /imp/ folder in the docker container
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock

# Run bundle install to install gems inside the gemfile
RUN gem install bundler --no-document
#RUN bundle install"
# Copy the whole app
COPY . .
RUN bundle install
RUN yarn install --check-files
#RUN RAILS_ENV=production ./bin/webpack
#RUN RAILS_ENV=production rails assets:precompile

EXPOSE 3000
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
