version: '3'
volumes:
  postgres_data: {}
services:
  app:
    # build:
    #   context: .
    #   dockerfile: ./docker/app/DockerFile
    image: namthp99/imp_app:1.0
    command: bundle exec puma -e production --pidfile /var/run/imp.pid
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    # build:
    #   context: .
    #   dockerfile: ./docker/web/DockerFile
    image: namthp99/imp_web:1.0
    depends_on:
      - app
    ports:
      - 80:80
