version: '3'
volumes:
  postgres_data: {}
services:
  app:
    # build:
    #   context: .
    #   dockerfile: ./docker/app/DockerFile
    image: namthp99/imp_app:1.0
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      DATABASE_DEVELOPMENT_HOST: db
      RAILS_ENV: "development"
      REDIS_DEVELOPMENT_URL: "redis://redis:6379"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: bunbuimp
      POSTGRES_DB: imp_development
      POSTGRES_HOST: db
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - ../../tmp/db:/var/lib/redis/data
