export default {
  setStatusCheckIn: 'SET_STATUS_CHECK_IN',
  setStatusCheckOut: 'SET_STATUS_CHECK_OUT',
  setAllDateStaff: 'SET_ALL_DATE_STAFF',
  setStaffList: 'SET_STAFF_LIST',
  setAllUser: 'SET_ALL_USER',
  GET_DAYOFF: 'GET_DAYOFF',
  ADD_DAYOFF: 'ADD_DAYOFF',
  UPDATE_DAYOFF: 'UPDATE_DAYOFF',
  GET_OVERTIMES: 'GET_OVERTIMES',
  ADD_OVERTIMES: 'ADD_OVERTIMES',
  UPDATE_OVERTIMES: 'UPDATE_OVERTIMES',
};
