export default {
  setCurrentUser: 'SET_CURRENT_USER',
  setTimeSheet: 'SET_STAFF_TIME_SHEET',
  SET_UPDATE_TIMESHEETS: 'SET_UPDATE_TIMESHEETS',
  EDIT_REASON_CHECKIN_CHECKOUT: 'EDIT_REASON_CHECKIN_CHECKOUT',
  GET_LIST_REQUEST_EDIT: 'GET_LIST_REQUEST_EDIT',
  SET_CONFIRMATION_STATUS_EDIT: 'SET_CONFIRMATION_STATUS_EDIT',
  GET_DETAIL_TIMESHEET_STAFF: 'GET_DETAIL_TIMESHEET_STAFF',
  GET_DETAIL_TIMESHEET_ADMIN: 'GET_DETAIL_TIMESHEET_ADMIN',
  GET_LIST_REQUEST_STAFF: 'GET_LIST_REQUEST_STAFF',
  EDIT_REQUEST_STAFF: 'EDIT_REQUEST_STAFF',
  ADD_REQUEST_STAFF: 'ADD_REQUEST_STAFF'
};
